import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import Providers from "@/lib/providers/Providers";
import Link from "next/link";
import {Button} from "@/components/ui/button";

const helvetica = localFont({
  src: "./fonts/Helvetica.ttf",
  variable: "--font-helvetica",
  weight: "400 700",
});
const montserrat = localFont({
  src: "./fonts/Montserrat-VariableFont_wght.ttf",
  variable: "--font-montserrat",
  weight: "400 500 600 700 800",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helvetica.variable} ${montserrat.variable} antialiased`}
      >
      <Providers>
        <div className="flex gap-4">
          <Link href={"/about"}>
            <Button variant={"ghost"}>
              About
            </Button>
          </Link>
          <Link href={"/"}>
            <Button variant={"ghost"}>
              Home
            </Button>
          </Link>
        </div>
        {children}
      </Providers>
      </body>
    </html>
  );
}

